#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-listen
Version  : 2.10.1
Release  : 1
URL      : https://rubygems.org/downloads/listen-2.10.1.gem
Source0  : https://rubygems.org/downloads/listen-2.10.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-listen-bin
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rb-fsevent
BuildRequires : rubygem-rb-inotify
BuildRequires : rubygem-rdoc

%description
### :warning: Listen is [looking for new maintainers](https://groups.google.com/forum/#!topic/guard-dev/2Td0QTvTIsE). Please [contact me](mailto:thibaud@thibaud.gg) if you're interested.

%package bin
Summary: bin components for the rubygem-listen package.
Group: Binaries

%description bin
bin components for the rubygem-listen package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n listen-2.10.1
gem spec %{SOURCE0} -l --ruby > rubygem-listen.gemspec

%build
gem build rubygem-listen.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
listen-2.10.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/listen-2.10.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/BSD/_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/BSD/_configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/BSD/_event_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/BSD/_find-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/BSD/_process_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/BSD/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/BSD/_watch_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/BSD/_watch_for_new_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/BSD/cdesc-BSD.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/BSD/usable%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/_log-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/_log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/_log_exception-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/_queue_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/local_fs%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Base/usable%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Darwin/_configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Darwin/_process_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Darwin/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Darwin/cdesc-Darwin.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Linux/_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Linux/_configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Linux/_dir_event%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Linux/_process_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Linux/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Linux/_skip_event%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Linux/cdesc-Linux.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Polling/_configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Polling/_process_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Polling/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Polling/cdesc-Polling.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/TCP/buffer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/TCP/cdesc-TCP.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/TCP/finalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/TCP/handle_data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/TCP/handle_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/TCP/local_fs%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/TCP/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/TCP/socket-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/TCP/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Windows/_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Windows/_configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Windows/_process_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Windows/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Windows/cdesc-Windows.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/Windows/usable%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/_log-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/_usable_adapter_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/_warn_polling_fallback-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/cdesc-Adapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Adapter/select-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/CLI/cdesc-CLI.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/CLI/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Change/_log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Change/cdesc-Change.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Change/change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Change/listener-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Change/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Directory/_async_changes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Directory/_change-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Directory/_log-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Directory/cdesc-Directory.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Directory/scan-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/File/cdesc-File.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/File/change-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/File/inaccurate_mac_time%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Forwarder/cdesc-Forwarder.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Forwarder/logger-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Forwarder/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Forwarder/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/Logging/_debug-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/Logging/_error_exception-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/Logging/_format_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/Logging/_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/Logging/_log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/Logging/_warn-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/Logging/cdesc-Logging.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/ThreadPool/add-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/ThreadPool/cdesc-ThreadPool.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/ThreadPool/stop-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Internals/cdesc-Internals.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_adapter_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_debug_level-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_init_actors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_init_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_init_tcp_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_process_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_queue_raw_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_reconfigure_silencer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_silenced%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_start_adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_start_wait_thread-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_stop_wait_thread-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_wait_for_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/_wakeup_wait_thread-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/async-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/cdesc-Listener.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/directories-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/host-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/ignore%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/listen%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/only-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/pause-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/paused%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/paused%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/paused-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/port-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/processing%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/queue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/registry-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/silencer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/supervisor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/sync-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/unpause-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Listener/wait_thread-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Options/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Options/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/QueueOptimizer/_calculate_add_remove_difference-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/QueueOptimizer/_detect_possible_editor_save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/QueueOptimizer/_logical_action_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/QueueOptimizer/_reinterpret_related_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/QueueOptimizer/_smoosh_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/QueueOptimizer/_squash_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/QueueOptimizer/cdesc-QueueOptimizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/_join-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/cdesc-Entry.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/children-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/meta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/real_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/record_dir_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/relative-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/Entry/sys_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/SymlinkDetector/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/SymlinkDetector/_fail-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/SymlinkDetector/cdesc-SymlinkDetector.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/SymlinkDetector/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/SymlinkDetector/verify_unwatched%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/_auto_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/_fast_build-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/_fast_build_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/_fast_try_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/_fast_unset_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/_fast_update_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/add_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/build-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/cdesc-Record.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/dir_entries-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/file_data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/listener-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/unset_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Record/update_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Silencer/_init_ignores-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Silencer/cdesc-Silencer.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Silencer/configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Silencer/ignore_patterns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Silencer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Silencer/only_patterns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Silencer/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/Silencer/silenced%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Broadcaster/_log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Broadcaster/_unicast-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Broadcaster/broadcast-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Broadcaster/cdesc-Broadcaster.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Broadcaster/finalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Broadcaster/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Broadcaster/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Broadcaster/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Message/body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Message/cdesc-Message.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Message/from_buffer-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Message/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Message/object%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Message/object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Message/payload%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Message/payload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/Message/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/TCP/cdesc-TCP.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/_add_listener-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/cdesc-Listen.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/on-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/stop-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/Listen/to-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-2.10.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/bin/listen
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/adapter/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/adapter/bsd.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/adapter/darwin.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/adapter/linux.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/adapter/polling.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/adapter/tcp.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/adapter/windows.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/change.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/directory.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/file.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/internals/logging.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/internals/thread_pool.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/listener.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/options.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/queue_optimizer.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/record.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/record/entry.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/record/symlink_detector.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/silencer.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/tcp.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/tcp/broadcaster.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/tcp/message.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-2.10.1/lib/listen/version.rb
/usr/lib64/ruby/gems/2.2.0/specifications/listen-2.10.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/listen
