#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-listen
Version  : 3.0.6
Release  : 3
URL      : https://rubygems.org/downloads/listen-3.0.6.gem
Source0  : https://rubygems.org/downloads/listen-3.0.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-listen-bin
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rb-fsevent
BuildRequires : rubygem-rb-inotify
BuildRequires : rubygem-rdoc

%description
:exclamation: Listen is currently accepting more maintainers. Please [read this](https://github.com/guard/guard/wiki/Maintainers) if you're interested in joining the team.

%package bin
Summary: bin components for the rubygem-listen package.
Group: Binaries

%description bin
bin components for the rubygem-listen package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n listen-3.0.6
gem spec %{SOURCE0} -l --ruby > rubygem-listen.gemspec

%build
gem build rubygem-listen.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
listen-3.0.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/listen-3.0.6.gem
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/BSD/_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/BSD/_configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/BSD/_event_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/BSD/_find-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/BSD/_process_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/BSD/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/BSD/_watch_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/BSD/_watch_for_new_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/BSD/cdesc-BSD.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/BSD/usable%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/_log-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/_log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/_log_exception-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/_queue_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/_stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/_timed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/started%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Base/usable%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Config/adapter_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Config/directories-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Config/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Config/queue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Config/silencer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Darwin/_configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Darwin/_process_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Darwin/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Darwin/_run_worker-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Darwin/_run_workers_in_background-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Darwin/_to_array-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Darwin/cdesc-Darwin.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Linux/_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Linux/_configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Linux/_dir_event%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Linux/_process_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Linux/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Linux/_skip_event%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Linux/_stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Linux/cdesc-Linux.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Polling/_configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Polling/_process_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Polling/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Polling/cdesc-Polling.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Windows/_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Windows/_configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Windows/_process_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Windows/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Windows/cdesc-Windows.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/Windows/usable%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/_log-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/_usable_adapter_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/_warn_polling_fallback-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/cdesc-Adapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Adapter/select-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Backend/adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Backend/cdesc-Backend.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Backend/min_delay_between_events-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Backend/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Backend/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Backend/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/CLI/cdesc-CLI.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/CLI/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Change/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Change/Config/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Change/Config/queue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Change/Config/silenced%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Change/cdesc-Change.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Change/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Change/invalidate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Change/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Change/record-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Directory/_async_changes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Directory/_change-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Directory/cdesc-Directory.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Directory/scan-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/callable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/event_queue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/listener-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/min_delay_between_events-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/optimize_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/paused%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/sleep-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/stopped%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Config/timestamp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/Error/NotStarted/cdesc-NotStarted.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/_nice_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/_sleep-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/_wait_for_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/_wait_until_resumed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/_wakeup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/cdesc-Loop.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/pause-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/paused%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/processing%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/resume-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/state-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/stopped%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/wait_thread-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Loop/wakeup_on_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/Stopped/cdesc-Stopped.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_check_stopped-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_deadline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_flush_wakeup_reasons-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_process_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_remember_time_of_first_unprocessed_event-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_reset_no_unprocessed_events-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_sleep-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_timestamp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_wait_until_events-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_wait_until_events_calm_down-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/_wait_until_no_longer_paused-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/cdesc-Processor.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/loop_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Processor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/Config/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/Config/relative%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/_safe_relative_from_cwd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/cdesc-Queue.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/event_queue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/Queue/pop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Event/cdesc-Event.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/ClassMethods/default_state-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/ClassMethods/state-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/ClassMethods/states-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/State/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/State/cdesc-State.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/State/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/State/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/State/transitions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/State/valid_transition%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/cdesc-FSM.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/current_state-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/current_state_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/default_state-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/state-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/states-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/transition%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/transition-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/transition_with_callbacks%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/FSM/validate_and_sanitize_new_state-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/File/cdesc-File.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/File/change-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/File/inaccurate_mac_time%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Forwarder/cdesc-Forwarder.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Forwarder/logger-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Forwarder/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Forwarder/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Internals/ThreadPool/add-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Internals/ThreadPool/cdesc-ThreadPool.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Internals/ThreadPool/stop-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Internals/cdesc-Internals.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/Config/adapter_instance_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/Config/adapter_select_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/Config/min_delay_between_events-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/Config/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/Config/relative%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/Config/silencer_rules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/backend-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/cdesc-Listener.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/ignore%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/only-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/pause-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/paused%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/processing%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/processor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Listener/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Logger/cdesc-Logger.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Options/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Options/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/Config/debug-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/Config/exist%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/Config/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/Config/silenced%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/_calculate_add_remove_difference-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/_detect_possible_editor_save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/_logical_action_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/_reinterpret_related_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/_squash_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/cdesc-QueueOptimizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/QueueOptimizer/smoosh_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/_join-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/cdesc-Entry.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/children-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/meta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/real_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/record_dir_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/relative-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/Entry/sys_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/SymlinkDetector/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/SymlinkDetector/_fail-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/SymlinkDetector/cdesc-SymlinkDetector.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/SymlinkDetector/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/SymlinkDetector/verify_unwatched%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/_auto_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/_fast_build_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/_fast_try_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/_fast_unset_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/_fast_update_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/add_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/build-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/cdesc-Record.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/dir_entries-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/file_data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/tree-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/unset_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Record/update_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/Controller/_reconfigure_silencer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/Controller/append_ignores-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/Controller/cdesc-Controller.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/Controller/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/Controller/replace_with_bang_ignores-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/Controller/replace_with_only-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/_init_ignores-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/cdesc-Silencer.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/ignore_patterns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/only_patterns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/Silencer/silenced%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/cdesc-Listen.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/logger%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/logger-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/setup_default_logger_if_unset-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/stop-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/Listen/to-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/listen-3.0.6/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/README.md
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/bin/listen
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/adapter/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/adapter/bsd.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/adapter/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/adapter/darwin.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/adapter/linux.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/adapter/polling.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/adapter/windows.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/backend.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/change.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/directory.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/event/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/event/loop.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/event/processor.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/event/queue.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/file.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/fsm.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/internals/thread_pool.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/listener.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/listener/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/logger.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/options.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/queue_optimizer.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/record.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/record/entry.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/record/symlink_detector.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/silencer.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/silencer/controller.rb
/usr/lib64/ruby/gems/2.2.0/gems/listen-3.0.6/lib/listen/version.rb
/usr/lib64/ruby/gems/2.2.0/specifications/listen-3.0.6.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/listen
